name: Deploy Environment Variables to SwipEats Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Environment Variables + Reconfigure .htaccess
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DCISM_HOST }}
          username: ${{ secrets.DCISM_USERNAME }}
          password: ${{ secrets.DCISM_PASSWORD }}
          port: ${{ secrets.DCISM_PORT }}
          script: |
            # Navigate to the server directory
            cd ${{ secrets.DCISM_DOMAIN }}/server
            
            
            # Configure .env files
            cat <<EOF > .env
            PORT=${{ secrets.SERVER_PORT }}

            DB_PORT=${{ secrets.DB_PORT }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}

            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOF

            cd ..

            # Reconfigure .htaccess
            cat <<EOF > .htaccess
            DirectoryIndex disabled

            RewriteEngine on

            RewriteCond %{SERVER_PORT} 80
            RewriteRule ^.*$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

            RewriteRule (.*) http://127.0.0.1:${{ secrets.SERVER_PORT }}%{REQUEST_URI} [P,L]
            EOF

